<!DOCTYPE html>
<html lang="en"><head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="robots" content="index, follow" />
	<meta name="googlebot" content="index, follow, noarchive" />
	<title>RajneetK-Fundamentals of Analytics</title>
	<link rel="icon" href="/favicon.ico" />
	<meta name="description" content="This the website for my Course Fundamentals of Analytics" />

	<meta name="generator" content="Hugo 0.83.1" />

	

	<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Fitting and interpreting models"/>
<meta name="twitter:description" content="#Data: Paris Paintings
pp &lt;- read_csv(&quot;paris-paintings.csv&quot;, na = c(&quot;n/a&quot;, &quot;&quot;, &quot;NA&quot;))## ## -- Column specification --------------------------------------------------------## cols(## .default = col_double(),## name = col_character(),## sale = col_character(),## lot = col_character(),## dealer = col_character(),## origin_author = col_character(),## origin_cat = col_character(),## school_pntg = col_character(),## price = col_number(),## subject = col_character(),## authorstandard = col_character(),## authorstyle = col_character(),## author = col_character(),## winningbidder = col_character(),## winningbiddertype = col_character(),## endbuyer = col_character(),## type_intermed = col_character(),## Shape = col_character(),## material = col_character(),## mat = col_character(),## materialCat = col_character()## )## i Use `spec()` for the full column specifications."/>

	<meta property="og:title" content="Fitting and interpreting models" />
<meta property="og:description" content="#Data: Paris Paintings
pp &lt;- read_csv(&quot;paris-paintings.csv&quot;, na = c(&quot;n/a&quot;, &quot;&quot;, &quot;NA&quot;))## ## -- Column specification --------------------------------------------------------## cols(## .default = col_double(),## name = col_character(),## sale = col_character(),## lot = col_character(),## dealer = col_character(),## origin_author = col_character(),## origin_cat = col_character(),## school_pntg = col_character(),## price = col_number(),## subject = col_character(),## authorstandard = col_character(),## authorstyle = col_character(),## author = col_character(),## winningbidder = col_character(),## winningbiddertype = col_character(),## endbuyer = col_character(),## type_intermed = col_character(),## Shape = col_character(),## material = col_character(),## mat = col_character(),## materialCat = col_character()## )## i Use `spec()` for the full column specifications." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/2021/06/15/fitting-and-interpreting-models/" /><meta property="article:section" content="post" />
<meta property="article:published_time" content="2021-06-15T00:00:00&#43;00:00" />
<meta property="article:modified_time" content="2021-06-15T00:00:00&#43;00:00" />



	
	<style>
	:root {
		 
		--text:  #fdfdfd ;
		--background:  #282a36 ;
		--accent:  #44475a ;
		--foreground:  #f8f8f2 ;
		--separator:  #6272a4 ;
		--cyan:  #8be9fd ;
		--green:  #50fa7b ;
		--orange:  #ffb86c ;
		--pink:  #ff79c6 ;
		--purple:  #bd93f9 ;
		--red:  #ff5555 ;
		--yellow:  #f1fa8c ;

		 
		--base:  1em ;
		--p:  1.25em ;
		--h4:  1.563em ;
		--h3:  1.953em ;
		--h2:  2.2441em ;
		--h1:  3.052em ;
	}
</style>














<link rel="stylesheet" href="/css/bundle.min.css">



	
	
</head><body>
	

	<main class="main">
<article class="single">
    
    

    
    <header class="single__header bkg-image" style=" ">
        <h1 class="single__header__title">Fitting and interpreting models</h1>

        
        <p class="single__header__date">
            
            June 15, 2021
            
        </p>
        

        
        <p class="single__header__author">
            By Rajneetk
        </p>
        

        

    </header>

    
    <main class="single__content">
        
<script src="/2021/06/15/fitting-and-interpreting-models/index_files/header-attrs/header-attrs.js"></script>
<script src="/2021/06/15/fitting-and-interpreting-models/index_files/kePrint/kePrint.js"></script>
<link href="/2021/06/15/fitting-and-interpreting-models/index_files/lightable/lightable.css" rel="stylesheet" />


<p>#Data: Paris Paintings</p>
<pre class="r"><code>pp &lt;- read_csv(&quot;paris-paintings.csv&quot;, na = c(&quot;n/a&quot;, &quot;&quot;, &quot;NA&quot;))</code></pre>
<pre><code>## 
## -- Column specification --------------------------------------------------------
## cols(
##   .default = col_double(),
##   name = col_character(),
##   sale = col_character(),
##   lot = col_character(),
##   dealer = col_character(),
##   origin_author = col_character(),
##   origin_cat = col_character(),
##   school_pntg = col_character(),
##   price = col_number(),
##   subject = col_character(),
##   authorstandard = col_character(),
##   authorstyle = col_character(),
##   author = col_character(),
##   winningbidder = col_character(),
##   winningbiddertype = col_character(),
##   endbuyer = col_character(),
##   type_intermed = col_character(),
##   Shape = col_character(),
##   material = col_character(),
##   mat = col_character(),
##   materialCat = col_character()
## )
## i Use `spec()` for the full column specifications.</code></pre>
<p>#Goal: Predict height from width
<span class="math display">\[\widehat{height}_{i} = \beta_0 + \beta_1 \times width_{i}\]</span>
<img src="/2021/06/15/fitting-and-interpreting-models/index_files/figure-html/height-width-plot-1.png" width="672" /></p>
<p><img src="tidymodels.png" width="98%" /></p>
<div id="step-1-specify-model" class="section level2">
<h2>Step 1: Specify model</h2>
<pre class="r"><code>linear_reg()</code></pre>
<pre><code>## Linear Regression Model Specification (regression)</code></pre>
</div>
<div id="step-2-set-model-fitting-engine" class="section level2">
<h2>Step 2: Set model fitting <em>engine</em></h2>
<pre class="r"><code>linear_reg() %&gt;%
  set_engine(&quot;lm&quot;) # lm: linear model</code></pre>
<pre><code>## Linear Regression Model Specification (regression)
## 
## Computational engine: lm</code></pre>
</div>
<div id="step-3-fit-model-estimate-parameters" class="section level2">
<h2>Step 3: Fit model &amp; estimate parameters</h2>
<pre class="r"><code>linear_reg() %&gt;%
  set_engine(&quot;lm&quot;) %&gt;%
  fit(Height_in ~ Width_in, data = pp)</code></pre>
<pre><code>## parsnip model object
## 
## Fit time:  21ms 
## 
## Call:
## stats::lm(formula = Height_in ~ Width_in, data = data)
## 
## Coefficients:
## (Intercept)     Width_in  
##      3.6214       0.7808</code></pre>
</div>
<div id="a-tidy-look-at-model-output" class="section level2">
<h2>A tidy look at model output</h2>
<pre class="r"><code>linear_reg() %&gt;%
  set_engine(&quot;lm&quot;) %&gt;%
  fit(Height_in ~ Width_in, data = pp) %&gt;%
  tidy()</code></pre>
<pre><code>## # A tibble: 2 x 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)    3.62    0.254        14.3 8.82e-45
## 2 Width_in       0.781   0.00950      82.1 0</code></pre>
</div>
<div id="visualizing-residuals" class="section level2">
<h2>Visualizing residuals</h2>
<p><img src="/2021/06/15/fitting-and-interpreting-models/index_files/figure-html/vis-res-1-1.png" width="70%" /></p>
</div>
<div id="models-with-categorical-explanatory-variables-height-landscape-features" class="section level1">
<h1>Models with categorical explanatory variables (Height &amp; landscape features)</h1>
<pre class="r"><code>linear_reg() %&gt;%
  set_engine(&quot;lm&quot;) %&gt;%
  fit(Height_in ~ factor(landsALL), data = pp) %&gt;%
  tidy()</code></pre>
<pre><code>## # A tibble: 2 x 5
##   term              estimate std.error statistic  p.value
##   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)          22.7      0.328      69.1 0       
## 2 factor(landsALL)1    -5.65     0.532     -10.6 7.97e-26</code></pre>
<p>#Relationship between height and school</p>
<pre class="r"><code>linear_reg() %&gt;%
  set_engine(&quot;lm&quot;) %&gt;%
  fit(Height_in ~ school_pntg, data = pp) %&gt;%
  tidy()</code></pre>
<pre><code>## # A tibble: 7 x 5
##   term            estimate std.error statistic p.value
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)        14.0       10.0     1.40  0.162  
## 2 school_pntgD/FL     2.33      10.0     0.232 0.816  
## 3 school_pntgF       10.2       10.0     1.02  0.309  
## 4 school_pntgG        1.65      11.9     0.139 0.889  
## 5 school_pntgI       10.3       10.0     1.02  0.306  
## 6 school_pntgS       30.4       11.4     2.68  0.00744
## 7 school_pntgX        2.87      10.3     0.279 0.780</code></pre>
#Categorical predictor with 3+ levels
.pull-left-wide[
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
school_pntg
</th>
<th style="text-align:center;">
D_FL
</th>
<th style="text-align:center;">
F
</th>
<th style="text-align:center;">
G
</th>
<th style="text-align:center;">
I
</th>
<th style="text-align:center;">
S
</th>
<th style="text-align:center;">
X
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
D/FL
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
G
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
I
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
X
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
</tr>
</tbody>
</table>
<p>]
.pull-right-narrow[
.small[</p>
<pre><code>## # A tibble: 3,393 x 3
##    name      Height_in school_pntg
##    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;      
##  1 L1764-2          37 F          
##  2 L1764-3          18 I          
##  3 L1764-4          13 D/FL       
##  4 L1764-5a         14 F          
##  5 L1764-5b         14 F          
##  6 L1764-6           7 I          
##  7 L1764-7a          6 F          
##  8 L1764-7b          6 F          
##  9 L1764-8          15 I          
## 10 L1764-9a          9 D/FL       
## 11 L1764-9b          9 D/FL       
## 12 L1764-10a        16 X          
## 13 L1764-10b        16 X          
## 14 L1764-10c        16 X          
## 15 L1764-11         20 D/FL       
## 16 L1764-12a        14 D/FL       
## 17 L1764-12b        14 D/FL       
## 18 L1764-13a        15 D/FL       
## 19 L1764-13b        15 D/FL       
## 20 L1764-14         37 F          
## # ... with 3,373 more rows</code></pre>
<p>]
]</p>
<hr />
<div id="relationship-between-height-and-school" class="section level2">
<h2>Relationship between height and school</h2>
<p>.small[</p>
<ul>
<li><strong>Austrian school (A)</strong> paintings are expected, on average, to be <strong>14 inches</strong> tall.</li>
<li><strong>Dutch/Flemish school (D/FL)</strong> paintings are expected, on average, to be <strong>2.33 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>French school (F)</strong> paintings are expected, on average, to be <strong>10.2 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>German school (G)</strong> paintings are expected, on average, to be <strong>1.65 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>Italian school (I)</strong> paintings are expected, on average, to be <strong>10.3 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>Spanish school (S)</strong> paintings are expected, on average, to be <strong>30.4 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li>Paintings whose school is <strong>unknown (X)</strong> are expected, on average, to be <strong>2.87 inches taller</strong> than <em>Austrian school</em> paintings.
]</li>
</ul>
</div>
</div>

    </main>

    
    <footer class="single__footer">
        
    </footer>

</article>

	</main><footer class="footer" id="footer">

    
    

    
    

    
    

    
    <div class="footer__copy">
        
        © 2021 - RajneetK-Fundamentals of Analytics
        
    </div>

    
    




<script>
    let activeSW = false;
    
</script>

<script defer src="/sw.min.js"></script>
<script defer src="/js/bundle.min.js"></script>

    
    
    





<script defer src="" crossorigin="anonymous"></script>
    

</footer></body>

</html>