
<!DOCTYPE html>
<html lang="en" data-figures="" class="page">
  <head>
<title>A05 Assignment: EDA2 | Fundamentals of Analytics</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
  
<meta property="og:locale" content="en" />

<meta property="og:type" content="article">
<meta name="description" content="Exploratory Data Analysis of the Hotel Booking Demand
IntroductionThis data set contains booking information for a city hotel and a resort hotel, including …">
<meta name="twitter:card" content="summary" />
<meta name="twitter:creator" content="">
<meta name="twitter:title" content="A05 Assignment: EDA2" />
<meta property="og:url" content="/2021/06/18/a05-assignment-eda2/" />
<meta property="og:title" content="A05 Assignment: EDA2" />
<meta property="og:description" content="Exploratory Data Analysis of the Hotel Booking Demand
IntroductionThis data set contains booking information for a city hotel and a resort hotel, including …" />
<meta property="og:image" content="/" />

<link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon-32x32.png">
<link rel="manifest" href="/icons/site.webmanifest">

<link rel="canonical" href="/2021/06/18/a05-assignment-eda2/">

    

    
    
    <link rel="preload" href="/css/styles.44fa81034ff7ea86cc966ac19f3832410f69e9e3d934b6314f12db45aa441d85959a242feb02ce9c112be4b1d4df423eaccb9633ecba2c6204dda4cb4901fc55.css" integrity = "sha512-RPqBA0/36obMlmrBnzgyQQ9p6ePZNLYxTxLbRapEHYWVmiQv6wLOnBEr5LHU30I&#43;rMuWM&#43;y6LGIE3aTLSQH8VQ==" as="style" crossorigin="anonymous">
    <link rel="preload" href="/js/bundle.min.617c4c3549a10c9fe7e1bb91e87f0722f6a285b59e742c7123c755df9fb33530bae76060ebd303966dd0e1c09813e679f8042802b7fd059315ef1345f0429ad2.js" as="script" integrity=
    "sha512-YXxMNUmhDJ/n4buR6H8HIvaihbWedCxxI8dV35&#43;zNTC652Bg69MDlm3Q4cCYE&#43;Z5&#43;AQoArf9BZMV7xNF8EKa0g==" crossorigin="anonymous">

    
    <link rel="stylesheet" type="text/css" href="/css/styles.44fa81034ff7ea86cc966ac19f3832410f69e9e3d934b6314f12db45aa441d85959a242feb02ce9c112be4b1d4df423eaccb9633ecba2c6204dda4cb4901fc55.css" integrity="sha512-RPqBA0/36obMlmrBnzgyQQ9p6ePZNLYxTxLbRapEHYWVmiQv6wLOnBEr5LHU30I&#43;rMuWM&#43;y6LGIE3aTLSQH8VQ==" crossorigin="anonymous">
    
  </head>
  
  
    
  
  <body data-code="100" data-lines="false" id="documentTop">

<header class="nav_header" >
  <nav class="nav"><a href='/' class="nav_brand nav_item" title="Fundamentals of Analytics">
  <img src="" class="logo" alt="Fundamentals of Analytics">
  <div class="nav_close">
    <div><svg class="icon">
  <use xlink:href="#open-menu"></use>
</svg><svg class="icon">
  <use xlink:href="#closeme"></use>
</svg></div>
  </div>
</a>

    <div class='nav_body nav_body_left'>
      
      
      
        

  <div class="nav_parent">
    <a href="/about/" class="nav_item" title="About">About </a>
  </div>
  <div class="nav_parent">
    <a href="https://github.com/RajneetK" class="nav_item" title="GitHub">GitHub </a>
  </div>
  <div class="nav_parent">
    <a href="https://twitter.com/Rajneet74968819" class="nav_item" title="Twitter">Twitter </a>
  </div>
      
<div class='follow'>
<div class="color_mode">
  <input type="checkbox" class="color_choice" id="mode">
</div>

</div>

    </div>
  </nav>
</header>

    <main>
  
<div class="grid-inverse wrap content">
  <article class="post_content">
    <h1 class="post_title">A05 Assignment: EDA2</h1>
  <div class="post_meta">
    <span><svg class="icon">
  <use xlink:href="#calendar"></use>
</svg></span>
    <span class="post_date">
      Jun 18, 2021</span>
    <span class="post_time"> · 15 min read</span>
    <span class="page_only">&nbsp;·
  <div class="post_share">
    Share on:
    <a href="https://twitter.com/intent/tweet?text=A05%20Assignment%3a%20EDA2&url=%2f2021%2f06%2f18%2fa05-assignment-eda2%2f&tw_p=tweetbutton" class="twitter" title="Share on Twitter" target="_blank" rel="nofollow">
      <svg class="icon">
  <use xlink:href="#twitter"></use>
</svg>
    </a>
    <a href="https://www.facebook.com/sharer.php?u=%2f2021%2f06%2f18%2fa05-assignment-eda2%2f&t=A05%20Assignment%3a%20EDA2" class="facebook" title="Share on Facebook" target="_blank" rel="nofollow">
      <svg class="icon">
  <use xlink:href="#facebook"></use>
</svg>
    </a>
    <a href="#linkedinshare" id = "linkedinshare" class="linkedin" title="Share on LinkedIn" rel="nofollow">
      <svg class="icon">
  <use xlink:href="#linkedin"></use>
</svg>
    </a>
    <a href="/2021/06/18/a05-assignment-eda2/" title="Copy Link" class="link link_yank">
      <svg class="icon">
  <use xlink:href="#copy"></use>
</svg>
    </a>
  </div>
  </span>
  </div>

    
    
<script src="/2021/06/18/a05-assignment-eda2/index_files/header-attrs/header-attrs.js"></script>


<p>Exploratory Data Analysis of the Hotel Booking Demand</p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>This data set contains booking information for a city hotel and a resort hotel, including when the booking was made, length of stay, number of adults, children, and/or babies, and number of available parking spaces, among other things. All personally identifying information has been extracted from the data.
To gain insight from the data, we will conduct exploratory data analysis.</p>
<p><strong>Questions:</strong>
1) How would people that book the same hotels repeatedly behave?
2) How likely Would they cancel a booking?
3) What kind of meal plan would they choose?
4) How many days ahead of checking in would they book a hotel?</p>
<p>To answer these questions seattle reservation dataset is analyzed, which is publicly accessible data, available dataset on Kaggle.</p>
</div>
<div id="import-packages" class="section level1">
<h1>Import Packages</h1>
<p>First Import necessary packages and import the dataset.</p>
<div id="import-seattle-dataset-files" class="section level2">
<h2>Import Seattle dataset files</h2>
<pre><code>## Rows: 119,390
## Columns: 32
## $ hotel                          &lt;chr&gt; &quot;Resort Hotel&quot;, &quot;Resort Hotel&quot;, &quot;Resort~
## $ is_canceled                    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, ~
## $ lead_time                      &lt;dbl&gt; 342, 737, 7, 13, 14, 14, 0, 9, 85, 75, ~
## $ arrival_date_year              &lt;dbl&gt; 2015, 2015, 2015, 2015, 2015, 2015, 201~
## $ arrival_date_month             &lt;chr&gt; &quot;July&quot;, &quot;July&quot;, &quot;July&quot;, &quot;July&quot;, &quot;July&quot;,~
## $ arrival_date_week_number       &lt;dbl&gt; 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,~
## $ arrival_date_day_of_month      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ~
## $ stays_in_weekend_nights        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
## $ stays_in_week_nights           &lt;dbl&gt; 0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 4, 4, 4, ~
## $ adults                         &lt;dbl&gt; 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, ~
## $ children                       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
## $ babies                         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
## $ meal                           &lt;chr&gt; &quot;BB&quot;, &quot;BB&quot;, &quot;BB&quot;, &quot;BB&quot;, &quot;BB&quot;, &quot;BB&quot;, &quot;BB~
## $ country                        &lt;chr&gt; &quot;PRT&quot;, &quot;PRT&quot;, &quot;GBR&quot;, &quot;GBR&quot;, &quot;GBR&quot;, &quot;GBR~
## $ market_segment                 &lt;chr&gt; &quot;Direct&quot;, &quot;Direct&quot;, &quot;Direct&quot;, &quot;Corporat~
## $ distribution_channel           &lt;chr&gt; &quot;Direct&quot;, &quot;Direct&quot;, &quot;Direct&quot;, &quot;Corporat~
## $ is_repeated_guest              &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
## $ previous_cancellations         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
## $ previous_bookings_not_canceled &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
## $ reserved_room_type             &lt;chr&gt; &quot;C&quot;, &quot;C&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;C&quot;, &quot;C&quot;,~
## $ assigned_room_type             &lt;chr&gt; &quot;C&quot;, &quot;C&quot;, &quot;C&quot;, &quot;A&quot;, &quot;A&quot;, &quot;A&quot;, &quot;C&quot;, &quot;C&quot;,~
## $ booking_changes                &lt;dbl&gt; 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
## $ deposit_type                   &lt;chr&gt; &quot;No Deposit&quot;, &quot;No Deposit&quot;, &quot;No Deposit~
## $ agent                          &lt;chr&gt; &quot;NULL&quot;, &quot;NULL&quot;, &quot;NULL&quot;, &quot;304&quot;, &quot;240&quot;, &quot;~
## $ company                        &lt;chr&gt; &quot;NULL&quot;, &quot;NULL&quot;, &quot;NULL&quot;, &quot;NULL&quot;, &quot;NULL&quot;,~
## $ days_in_waiting_list           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
## $ customer_type                  &lt;chr&gt; &quot;Transient&quot;, &quot;Transient&quot;, &quot;Transient&quot;, ~
## $ adr                            &lt;dbl&gt; 0.00, 0.00, 75.00, 75.00, 98.00, 98.00,~
## $ required_car_parking_spaces    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ~
## $ total_of_special_requests      &lt;dbl&gt; 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 3, ~
## $ reservation_status             &lt;chr&gt; &quot;Check-Out&quot;, &quot;Check-Out&quot;, &quot;Check-Out&quot;, ~
## $ reservation_status_date        &lt;date&gt; 2015-07-01, 2015-07-01, 2015-07-02, 20~</code></pre>
</div>
</div>
<div id="dataset-link" class="section level1">
<h1>Dataset link</h1>
<div id="wstpwfklux" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#wstpwfklux .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wstpwfklux .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wstpwfklux .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wstpwfklux .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wstpwfklux .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wstpwfklux .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wstpwfklux .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wstpwfklux .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wstpwfklux .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wstpwfklux .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wstpwfklux .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wstpwfklux .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#wstpwfklux .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#wstpwfklux .gt_from_md > :first-child {
  margin-top: 0;
}

#wstpwfklux .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wstpwfklux .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wstpwfklux .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#wstpwfklux .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wstpwfklux .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#wstpwfklux .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wstpwfklux .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wstpwfklux .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wstpwfklux .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wstpwfklux .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wstpwfklux .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#wstpwfklux .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wstpwfklux .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#wstpwfklux .gt_left {
  text-align: left;
}

#wstpwfklux .gt_center {
  text-align: center;
}

#wstpwfklux .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wstpwfklux .gt_font_normal {
  font-weight: normal;
}

#wstpwfklux .gt_font_bold {
  font-weight: bold;
}

#wstpwfklux .gt_font_italic {
  font-style: italic;
}

#wstpwfklux .gt_super {
  font-size: 65%;
}

#wstpwfklux .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 65%;
}
</style>
<table class="gt_table">
  
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Name</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">link</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Hotel Booking Demand Dataset</td>
<td class="gt_row gt_center"><a href="https://www.kaggle.com/jessemostipak/hotel-booking-demand">Click here</a></td></tr>
  </tbody>
  
  
</table>
</div>
</div>
<div id="missing-value" class="section level1">
<h1>Missing value</h1>
<p>By examining the missing values for each variable, we can see that there are only four missing values for variable “children,” with no missing values in the other variables.</p>
<pre><code>##                          hotel                    is_canceled 
##                              0                              0 
##                      lead_time              arrival_date_year 
##                              0                              0 
##             arrival_date_month       arrival_date_week_number 
##                              0                              0 
##      arrival_date_day_of_month        stays_in_weekend_nights 
##                              0                              0 
##           stays_in_week_nights                         adults 
##                              0                              0 
##                       children                         babies 
##                              4                              0 
##                           meal                        country 
##                              0                              0 
##                 market_segment           distribution_channel 
##                              0                              0 
##              is_repeated_guest         previous_cancellations 
##                              0                              0 
## previous_bookings_not_canceled             reserved_room_type 
##                              0                              0 
##             assigned_room_type                booking_changes 
##                              0                              0 
##                   deposit_type                          agent 
##                              0                              0 
##                        company           days_in_waiting_list 
##                              0                              0 
##                  customer_type                            adr 
##                              0                              0 
##    required_car_parking_spaces      total_of_special_requests 
##                              0                              0 
##             reservation_status        reservation_status_date 
##                              0                              0</code></pre>
</div>
<div id="data-cleaning" class="section level1">
<h1>Data cleaning</h1>
<ol style="list-style-type: decimal">
<li><p>Take care of the missing value
The variable “children” has four missing values. The median value of this variable is used to impute them. Given the large sample size, this method would be appropriate.</p></li>
<li><p>Make data makes more sense</p></li>
</ol>
<p>The meal “Undefined” is imputed by “SC” because both “Undefined” and “SC” indicate that the customer chose not to eat at the hotel.</p>
<p>The variable “is repeated guest” is binary, it should be a factor. The same modification is required for the variable “is canceled.”</p>
<ol start="3" style="list-style-type: decimal">
<li>Statistical summary</li>
</ol>
<p>We can get some useful information from the statistical summary. For example, approximately 37% of bookings have been canceled. The booking data ranges from 2015 to 2017. Customers stay for two nights in half of the weekday bookings. Customers stay for three nights in 75% of the bookings. The longest stay possible is 50 nights. The average number of prior cancellations is less than one. One special request is made in 75% of all bookings. Repeat customers account for 3% of all bookings.</p>
<pre><code>##     hotel           is_canceled   lead_time   arrival_date_year
##  Length:119390      0:75166     Min.   :  0   Min.   :2015     
##  Class :character   1:44224     1st Qu.: 18   1st Qu.:2016     
##  Mode  :character               Median : 69   Median :2016     
##                                 Mean   :104   Mean   :2016     
##                                 3rd Qu.:160   3rd Qu.:2017     
##                                 Max.   :737   Max.   :2017     
##  arrival_date_month arrival_date_week_number arrival_date_day_of_month
##  Length:119390      Min.   : 1.00            Min.   : 1.0             
##  Class :character   1st Qu.:16.00            1st Qu.: 8.0             
##  Mode  :character   Median :28.00            Median :16.0             
##                     Mean   :27.17            Mean   :15.8             
##                     3rd Qu.:38.00            3rd Qu.:23.0             
##                     Max.   :53.00            Max.   :31.0             
##  stays_in_weekend_nights stays_in_week_nights     adults      
##  Min.   : 0.0000         Min.   : 0.0         Min.   : 0.000  
##  1st Qu.: 0.0000         1st Qu.: 1.0         1st Qu.: 2.000  
##  Median : 1.0000         Median : 2.0         Median : 2.000  
##  Mean   : 0.9276         Mean   : 2.5         Mean   : 1.856  
##  3rd Qu.: 2.0000         3rd Qu.: 3.0         3rd Qu.: 2.000  
##  Max.   :19.0000         Max.   :50.0         Max.   :55.000  
##     children           babies          meal         country         
##  Min.   : 0.0000   Min.   : 0.000000   BB:92310   Length:119390     
##  1st Qu.: 0.0000   1st Qu.: 0.000000   FB:  798   Class :character  
##  Median : 0.0000   Median : 0.000000   HB:14463   Mode  :character  
##  Mean   : 0.1039   Mean   : 0.007949   SC:11819                     
##  3rd Qu.: 0.0000   3rd Qu.: 0.000000                                
##  Max.   :10.0000   Max.   :10.000000                                
##  market_segment     distribution_channel is_repeated_guest
##  Length:119390      Length:119390        0:115580         
##  Class :character   Class :character     1:  3810         
##  Mode  :character   Mode  :character                      
##                                                           
##                                                           
##                                                           
##  previous_cancellations previous_bookings_not_canceled reserved_room_type
##  Min.   : 0.00000       Min.   : 0.0000                Length:119390     
##  1st Qu.: 0.00000       1st Qu.: 0.0000                Class :character  
##  Median : 0.00000       Median : 0.0000                Mode  :character  
##  Mean   : 0.08712       Mean   : 0.1371                                  
##  3rd Qu.: 0.00000       3rd Qu.: 0.0000                                  
##  Max.   :26.00000       Max.   :72.0000                                  
##  assigned_room_type booking_changes   deposit_type          agent          
##  Length:119390      Min.   : 0.0000   Length:119390      Length:119390     
##  Class :character   1st Qu.: 0.0000   Class :character   Class :character  
##  Mode  :character   Median : 0.0000   Mode  :character   Mode  :character  
##                     Mean   : 0.2211                                        
##                     3rd Qu.: 0.0000                                        
##                     Max.   :21.0000                                        
##    company          days_in_waiting_list customer_type           adr         
##  Length:119390      Min.   :  0.000      Length:119390      Min.   :  -6.38  
##  Class :character   1st Qu.:  0.000      Class :character   1st Qu.:  69.29  
##  Mode  :character   Median :  0.000      Mode  :character   Median :  94.58  
##                     Mean   :  2.321                         Mean   : 101.83  
##                     3rd Qu.:  0.000                         3rd Qu.: 126.00  
##                     Max.   :391.000                         Max.   :5400.00  
##  required_car_parking_spaces total_of_special_requests reservation_status
##  Min.   :0.00000             Min.   :0.0000            Length:119390     
##  1st Qu.:0.00000             1st Qu.:0.0000            Class :character  
##  Median :0.00000             Median :0.0000            Mode  :character  
##  Mean   :0.06252             Mean   :0.5714                              
##  3rd Qu.:0.00000             3rd Qu.:1.0000                              
##  Max.   :8.00000             Max.   :5.0000                              
##  reservation_status_date
##  Min.   :2014-10-17     
##  1st Qu.:2016-02-01     
##  Median :2016-08-07     
##  Mean   :2016-07-30     
##  3rd Qu.:2017-02-08     
##  Max.   :2017-09-14</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Glipse the data</li>
</ol>
<p>The dataset look clean and tidy now.</p>
<pre><code>## # A tibble: 20 x 32
##    hotel        is_canceled lead_time arrival_date_year arrival_date_month
##    &lt;chr&gt;        &lt;fct&gt;           &lt;dbl&gt;             &lt;dbl&gt; &lt;chr&gt;             
##  1 Resort Hotel 0                 342              2015 July              
##  2 Resort Hotel 0                 737              2015 July              
##  3 Resort Hotel 0                   7              2015 July              
##  4 Resort Hotel 0                  13              2015 July              
##  5 Resort Hotel 0                  14              2015 July              
##  6 Resort Hotel 0                  14              2015 July              
##  7 Resort Hotel 0                   0              2015 July              
##  8 Resort Hotel 0                   9              2015 July              
##  9 Resort Hotel 1                  85              2015 July              
## 10 Resort Hotel 1                  75              2015 July              
## 11 Resort Hotel 1                  23              2015 July              
## 12 Resort Hotel 0                  35              2015 July              
## 13 Resort Hotel 0                  68              2015 July              
## 14 Resort Hotel 0                  18              2015 July              
## 15 Resort Hotel 0                  37              2015 July              
## 16 Resort Hotel 0                  68              2015 July              
## 17 Resort Hotel 0                  37              2015 July              
## 18 Resort Hotel 0                  12              2015 July              
## 19 Resort Hotel 0                   0              2015 July              
## 20 Resort Hotel 0                   7              2015 July              
## # ... with 27 more variables: arrival_date_week_number &lt;dbl&gt;,
## #   arrival_date_day_of_month &lt;dbl&gt;, stays_in_weekend_nights &lt;dbl&gt;,
## #   stays_in_week_nights &lt;dbl&gt;, adults &lt;dbl&gt;, children &lt;dbl&gt;, babies &lt;dbl&gt;,
## #   meal &lt;fct&gt;, country &lt;chr&gt;, market_segment &lt;chr&gt;,
## #   distribution_channel &lt;chr&gt;, is_repeated_guest &lt;fct&gt;,
## #   previous_cancellations &lt;dbl&gt;, previous_bookings_not_canceled &lt;dbl&gt;,
## #   reserved_room_type &lt;chr&gt;, assigned_room_type &lt;chr&gt;, booking_changes &lt;dbl&gt;,
## #   deposit_type &lt;chr&gt;, agent &lt;chr&gt;, company &lt;chr&gt;, days_in_waiting_list &lt;dbl&gt;,
## #   customer_type &lt;chr&gt;, adr &lt;dbl&gt;, required_car_parking_spaces &lt;dbl&gt;,
## #   total_of_special_requests &lt;dbl&gt;, reservation_status &lt;chr&gt;,
## #   reservation_status_date &lt;date&gt;</code></pre>
</div>
<div id="exploration-data-analysis" class="section level1">
<h1>EXPLORATION DATA ANALYSIS</h1>
<ol style="list-style-type: decimal">
<li>Distribution of guests:</li>
</ol>
<p>According to the table and piechart below,3.19 percent of the guests are repeat visitors, while the rest are first-time visitors. Because people do not return to the same location repeatedly, these figures make sense.</p>
<pre><code>## # A tibble: 2 x 3
##   is_repeated_guest percent  total
##   &lt;fct&gt;               &lt;dbl&gt;  &lt;int&gt;
## 1 0                   96.8  115580
## 2 1                    3.19   3810</code></pre>
<p><img src="/2021/06/18/a05-assignment-eda2/index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<ol start="2" style="list-style-type: decimal">
<li>The difference in lead time between two groups of guests:</li>
</ol>
<p>I created the following two functions to display the visualization in order to investigate several behaviors of repeat visitors.</p>
<pre class="r"><code>guestbehaboxplot(hotel_data$lead_time)</code></pre>
<p><img src="/2021/06/18/a05-assignment-eda2/index_files/figure-html/unnamed-chunk-11-1.png" width="672" />
The lead time for the repeated guests are shorter than that of unrepeated guests significantly. The average lead time for the repeated guests is 31 days, while that for unrepeated guests is 106 days.</p>
<pre><code>## # A tibble: 2 x 2
##   is_repeated_guest  mean
##   &lt;fct&gt;             &lt;dbl&gt;
## 1 0                 106. 
## 2 1                  30.8</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>How often do repeat customers cancel their reservations?</li>
</ol>
<p>Unrepeated guests cancel 43672 bookings, accounting for 37.8 percent of total unrepeated guests. On the other hand, 552 repeat guests cancel their reservations, accounting for only 14.4 percent of the repeat group.</p>
<pre><code>##   is_repeated_guest         n
## 1                NA 0.3778508
## 2                NA 0.1448819</code></pre>
<ol start="4" style="list-style-type: decimal">
<li>Do previous guests cancel their reservations?</li>
</ol>
<p>Yes. 75.6 percent of returning guests have no cancellation history. The percentage of repeat visitors is 95.2 percent. This makes sense because unrepeated guests dress in an unrepeating manner. The average cancellation rate for repeat and non-repeated guests is 0.47 and 0.07, respectively.</p>
<p><img src="/2021/06/18/a05-assignment-eda2/index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre><code>##   is_repeated_guest         n
## 1                NA 0.9519207
## 2                NA 0.7566929</code></pre>
<pre><code>## # A tibble: 2 x 2
##   is_repeated_guest   mean
##   &lt;fct&gt;              &lt;dbl&gt;
## 1 0                 0.0745
## 2 1                 0.470</code></pre>
<ol start="5" style="list-style-type: decimal">
<li>How many bookings have not previously been cancelled?</li>
</ol>
<p>74.5 percent of repeat guests’ bookings have not been cancelled. Unrepeated visitors account for only 0.7 percent of all visitors. Previous bookings that have not been cancelled are 3.59 and 0.02, respectively, for repeat guests and unrepeated guests.</p>
<p><img src="/2021/06/18/a05-assignment-eda2/index_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre><code>##   is_repeated_guest           n
## 1                NA 0.006765876
## 2                NA 0.744881890</code></pre>
<pre><code>## # A tibble: 2 x 2
##   is_repeated_guest   mean
##   &lt;fct&gt;              &lt;dbl&gt;
## 1 0                 0.0234
## 2 1                 3.59</code></pre>
<ol start="6" style="list-style-type: decimal">
<li>What kind of hotel would returning guests choose?</li>
</ol>
<p>It turns out that City Hotel is preferred by repeat guests over Resort Hotel. However, 46.7 percent of repeat guests book Resort Hotel, while only 33.1 percent of unrepeated guests book Resort Hotel.</p>
<pre><code>##   is_repeated_guest         n
## 1                NA 0.3312165
## 2                NA 0.4666667</code></pre>
<ol start="7" style="list-style-type: decimal">
<li>Do returning guests change their reservations?</li>
</ol>
<p>81.1 percent of returning guests do not change their booking. This figure is slightly lower than that of unrepeated visitors.</p>
<p><img src="/2021/06/18/a05-assignment-eda2/index_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre><code>##   is_repeated_guest         n
## 1                NA 0.8498183
## 2                NA 0.8115486</code></pre>
<ol start="8" style="list-style-type: decimal">
<li>Meal preference of returning guests.</li>
</ol>
<p>When comparing the meal choices of repeat guests and unrepeated guests, repeat guests have a higher percentage of choosing Bed &amp; Breakfast and a lower percentage of choosing the other three types of meal plans.</p>
<pre><code>##     
##          0     1
##   BB 88837  3473
##   FB   789     9
##   HB 14277   186
##   SC 11677   142</code></pre>
<ol start="9" style="list-style-type: decimal">
<li>Do returning visitors leave a deposit?</li>
</ol>
<p>Normally no. 98.2% of repeated guests don’t make deposit. A possiable reason is that they are reliable guests, so that they don’t need to make deposit. The percentage for unrepeated guests is 87.3%.</p>
<pre><code>##   is_repeated_guest         n
## 1                NA 0.8729798
## 2                NA 0.9821522</code></pre>
<ol start="10" style="list-style-type: decimal">
<li>Do frequent visitors make special requests?</li>
</ol>
<p>Over half of them do not. 58.2 percent of returning guests do not make any special requests. This percentage is very close to that of first-time visitors.</p>
<pre><code>##   is_repeated_guest         n
## 1                NA 0.5892109
## 2                NA 0.5818898</code></pre>
<ol start="11" style="list-style-type: decimal">
<li>Customer type of returning visitors</li>
</ol>
<p>80.7 percent of returning guests make bookings that are not part of a group or contract and are unrelated to other transient bookings. Bookings associated with a group are made by 4.2 percent of repeat guests. Both of these figures are higher than the number of bookings made by first-time visitors.</p>
<pre><code>##   is_repeated_guest         n
## 1                NA 0.7487455
## 2                NA 0.8065617</code></pre>
<ol start="12" style="list-style-type: decimal">
<li>Distribution channel</li>
</ol>
<p><img src="/2021/06/18/a05-assignment-eda2/index_files/figure-html/unnamed-chunk-27-1.png" width="672" />
13) Histogram illustrating Days in waiting list and cancellations</p>
<p><img src="/2021/06/18/a05-assignment-eda2/index_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<p>#SUMMARY</p>
<ul>
<li><p>Only 3.19 percent of the guests are returning.</p></li>
<li><p>Repeated guests tend to book the hotel one month in advance of their visit, which is much shorter than that of first-time visitors. This indicates that repeat guests do not rush to book hotels because they always know which hotel to book if they visit that location.</p></li>
<li><p>The likelihood of a repeat guest cancelling a booking is much lower than that of an unrepeated guest. This indicates that returning visitors are extremely loyal.</p></li>
<li><p>75.6 percent of returning guests have no cancellation history. 74.5 percent of repeat guests’ bookings have not been cancelled. The average number of previous bookings that have not been cancelled is 3.59.</p></li>
<li><p>Guests who return prefer City Hotel slightly more than Resort Hotel. However, the percentage of people who choose Resort Hotel is higher than the percentage of people who choose unrepeated guests.</p></li>
<li><p>81.1 percent of returning guests do not change their booking.</p></li>
<li><p>When booking hotels, 91.1 percent of repeat guests select Bed &amp; Breakfast. Higher than infrequent visitors.</p></li>
<li><p>98.2 percent of returning guests do not make a deposit. Higher than infrequent visitors.</p></li>
<li><p>More than half of returning guests do not make special requests, almost as many as first-time visitors do.</p></li>
<li><p>80.7 percent of returning guests make bookings that are not part of a group or contract and are unrelated to other transient bookings.</p></li>
</ul>
</div>


  </article>
<aside class="sidebar">
  <section class="sidebar_inner">
    <h2 class="mt-4">Recent Posts</h2>
    <ul class="flex-column">
      <li>
        <a href="/2021/06/22/final-project/" class="nav-link" title="Final Project">Final Project</a>
      </li>
      <li>
        <a href="/2021/06/15/fitting-and-interpreting-models/" class="nav-link" title="Fitting and interpreting models">Fitting and interpreting models</a>
      </li>
      <li>
        <a href="/2021/06/04/a03-assignment-eda1/" class="nav-link" title="A03 Assignment EDA1">A03 Assignment EDA1</a>
      </li>
      <li>
        <a href="/2021/06/01/data-io/" class="nav-link" title="Data IO">Data IO</a>
      </li>
      <li>
        <a href="/2021/06/01/data-io-data-recoding/" class="nav-link" title="Data IO- Data Recoding">Data IO- Data Recoding</a>
      </li>
      <li>
        <a href="/2021/05/28/assignment-a02/" class="nav-link" title="Assignment A02">Assignment A02</a>
      </li>
      <li>
        <a href="/2021/05/25/data-wrangling-using-tidyverse/" class="nav-link" title="Data Wrangling using tidyverse">Data Wrangling using tidyverse</a>
      </li>
      <li>
        <a href="/2021/05/25/fun-with-r/" class="nav-link" title="Fun with R">Fun with R</a>
      </li>
    </ul>
    <div>
      <h2 class="mt-4 taxonomy" id="categories-section">Categories</h2>
      <nav class="tags_nav">
        <a href='/categories/data-analytics/' class="post_tag button button_translucent" title="data-analytics">
          DATA-ANALYTICS
          <span class="button_tally">8</span>
        </a>
        
        <a href='/categories/fun-with-r/' class="post_tag button button_translucent" title="fun-with-r">
          FUN-WITH-R
          <span class="button_tally">1</span>
        </a>
        
        <a href='/categories/ggplot2/' class="post_tag button button_translucent" title="ggplot2">
          GGPLOT2
          <span class="button_tally">1</span>
        </a>
        
        
      </nav>
    </div>
  </section>
</aside>

  
</div>
    </main><svg width="0" height="0" class="hidden">
  <symbol viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" id="facebook">
    <path d="M437 0H75C33.648 0 0 33.648 0 75v362c0 41.352 33.648 75 75 75h151V331h-60v-90h60v-61c0-49.629 40.371-90 90-90h91v90h-91v61h91l-15 90h-76v181h121c41.352 0 75-33.648 75-75V75c0-41.352-33.648-75-75-75zm0 0"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18.001 18.001" id="twitter">
    <path d="M15.891 4.013c.808-.496 1.343-1.173 1.605-2.034a8.68 8.68 0 0 1-2.351.861c-.703-.756-1.593-1.14-2.66-1.14-1.043 0-1.924.366-2.643 1.078a3.56 3.56 0 0 0-1.076 2.605c0 .309.039.585.117.819-3.076-.105-5.622-1.381-7.628-3.837-.34.601-.51 1.213-.51 1.846 0 1.301.549 2.332 1.645 3.089-.625-.053-1.176-.211-1.645-.47 0 .929.273 1.705.82 2.388a3.623 3.623 0 0 0 2.115 1.291c-.312.08-.641.118-.979.118-.312 0-.533-.026-.664-.083.23.757.664 1.371 1.291 1.841a3.652 3.652 0 0 0 2.152.743C4.148 14.173 2.625 14.69.902 14.69c-.422 0-.721-.006-.902-.038 1.697 1.102 3.586 1.649 5.676 1.649 2.139 0 4.029-.542 5.674-1.626 1.645-1.078 2.859-2.408 3.639-3.974a10.77 10.77 0 0 0 1.172-4.892v-.468a7.788 7.788 0 0 0 1.84-1.921 8.142 8.142 0 0 1-2.11.593z"
      ></path>
  </symbol>
  <symbol aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" id="mail">
    <path  d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" id="calendar">
    <path d="M452 40h-24V0h-40v40H124V0H84v40H60C26.916 40 0 66.916 0 100v352c0 33.084 26.916 60 60 60h392c33.084 0 60-26.916 60-60V100c0-33.084-26.916-60-60-60zm20 412c0 11.028-8.972 20-20 20H60c-11.028 0-20-8.972-20-20V188h432v264zm0-304H40v-48c0-11.028 8.972-20 20-20h24v40h40V80h264v40h40V80h24c11.028 0 20 8.972 20 20v48z"></path>
    <path d="M76 230h40v40H76zm80 0h40v40h-40zm80 0h40v40h-40zm80 0h40v40h-40zm80 0h40v40h-40zM76 310h40v40H76zm80 0h40v40h-40zm80 0h40v40h-40zm80 0h40v40h-40zM76 390h40v40H76zm80 0h40v40h-40zm80 0h40v40h-40zm80 0h40v40h-40zm80-80h40v40h-40z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" id="github">
    <path d="M255.968 5.329C114.624 5.329 0 120.401 0 262.353c0 113.536 73.344 209.856 175.104 243.872 12.8 2.368 17.472-5.568 17.472-12.384 0-6.112-.224-22.272-.352-43.712-71.2 15.52-86.24-34.464-86.24-34.464-11.616-29.696-28.416-37.6-28.416-37.6-23.264-15.936 1.728-15.616 1.728-15.616 25.696 1.824 39.2 26.496 39.2 26.496 22.848 39.264 59.936 27.936 74.528 21.344 2.304-16.608 8.928-27.936 16.256-34.368-56.832-6.496-116.608-28.544-116.608-127.008 0-28.064 9.984-51.008 26.368-68.992-2.656-6.496-11.424-32.64 2.496-68 0 0 21.504-6.912 70.4 26.336 20.416-5.696 42.304-8.544 64.096-8.64 21.728.128 43.648 2.944 64.096 8.672 48.864-33.248 70.336-26.336 70.336-26.336 13.952 35.392 5.184 61.504 2.56 68 16.416 17.984 26.304 40.928 26.304 68.992 0 98.72-59.84 120.448-116.864 126.816 9.184 7.936 17.376 23.616 17.376 47.584 0 34.368-.32 62.08-.32 70.496 0 6.88 4.608 14.88 17.6 12.352C438.72 472.145 512 375.857 512 262.353 512 120.401 397.376 5.329 255.968 5.329z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 212 212" id="gitlab">
    <path d="M12.3 74.7h54L43.3 3c-1-3.6-6.4-3.6-7.6 0L12.3 74.8z" />
    <path d="M12.3 74.7L.5 111c-1 3.2 0 6.8 3 8.8l101.6 74-92.5-119z"/>
    <path d="M105 193.7l-38.6-119h-54l92.7 119z"/>
    <path d="M105 193.7l38.7-119H66.4l38.7 119z"/>
    <path d="M105 193.7l38.7-119H198l-93 119z"/>
    <path d="M198 74.7l11.6 36.2c1 3 0 6.6-3 8.6l-101.5 74 93-119z"/>
    <path d="M198 74.7h-54.3L167 3c1.2-3.6 6.4-3.6 7.6 0L198 74.8z"/> 
  </symbol>
  <symbol viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" id="rss">
    <circle cx="3.429" cy="20.571" r="3.429"></circle>
    <path d="M11.429 24h4.57C15.999 15.179 8.821 8.001 0 8v4.572c6.302.001 11.429 5.126 11.429 11.428z"></path>
    <path d="M24 24C24 10.766 13.234 0 0 0v4.571c10.714 0 19.43 8.714 19.43 19.429z"></path>
  </symbol>
  <symbol viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" id="linkedin">
    <path d="M437 0H75C33.648 0 0 33.648 0 75v362c0 41.352 33.648 75 75 75h362c41.352 0 75-33.648 75-75V75c0-41.352-33.648-75-75-75zM181 406h-60V196h60zm0-240h-60v-60h60zm210 240h-60V286c0-16.54-13.46-30-30-30s-30 13.46-30 30v120h-60V196h60v11.309C286.719 202.422 296.93 196 316 196c40.691.043 75 36.547 75 79.688zm0 0"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 612 612" id="arrow">
    <path d="M604.501 440.509L325.398 134.956c-5.331-5.357-12.423-7.627-19.386-7.27-6.989-.357-14.056 1.913-19.387 7.27L7.499 440.509c-9.999 10.024-9.999 26.298 0 36.323s26.223 10.024 36.222 0l262.293-287.164L568.28 476.832c9.999 10.024 26.222 10.024 36.221 0 9.999-10.023 9.999-26.298 0-36.323z"></path>
  </symbol>
  <symbol viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" id="carly">
    <path d="M504.971 239.029L448 182.059V84c0-46.317-37.682-84-84-84h-44c-13.255 0-24 10.745-24 24s10.745 24 24 24h44c19.851 0 36 16.149 36 36v108c0 6.365 2.529 12.47 7.029 16.971L454.059 256l-47.029 47.029A24.002 24.002 0 0 0 400 320v108c0 19.851-16.149 36-36 36h-44c-13.255 0-24 10.745-24 24s10.745 24 24 24h44c46.318 0 84-37.683 84-84v-98.059l56.971-56.971c9.372-9.372 9.372-24.568 0-33.941zM112 192V84c0-19.851 16.149-36 36-36h44c13.255 0 24-10.745 24-24S205.255 0 192 0h-44c-46.318 0-84 37.683-84 84v98.059l-56.971 56.97c-9.373 9.373-9.373 24.568 0 33.941L64 329.941V428c0 46.317 37.682 84 84 84h44c13.255 0 24-10.745 24-24s-10.745-24-24-24h-44c-19.851 0-36-16.149-36-36V320c0-6.365-2.529-12.47-7.029-16.971L57.941 256l47.029-47.029A24.002 24.002 0 0 0 112 192z"></path>
  </symbol>
  <symbol viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" id="copy">
    <path d="M23 2.75A2.75 2.75 0 0 0 20.25 0H8.75A2.75 2.75 0 0 0 6 2.75v13.5A2.75 2.75 0 0 0 8.75 19h11.5A2.75 2.75 0 0 0 23 16.25zM18.25 14.5h-7.5a.75.75 0 0 1 0-1.5h7.5a.75.75 0 0 1 0 1.5zm0-3h-7.5a.75.75 0 0 1 0-1.5h7.5a.75.75 0 0 1 0 1.5zm0-3h-7.5a.75.75 0 0 1 0-1.5h7.5a.75.75 0 0 1 0 1.5z"></path>
    <path d="M8.75 20.5a4.255 4.255 0 0 1-4.25-4.25V2.75c0-.086.02-.166.025-.25H3.75A2.752 2.752 0 0 0 1 5.25v16A2.752 2.752 0 0 0 3.75 24h12a2.752 2.752 0 0 0 2.75-2.75v-.75z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512.001 512.001" id="closeme">
    <path d="M284.286 256.002L506.143 34.144c7.811-7.811 7.811-20.475 0-28.285-7.811-7.81-20.475-7.811-28.285 0L256 227.717 34.143 5.859c-7.811-7.811-20.475-7.811-28.285 0-7.81 7.811-7.811 20.475 0 28.285l221.857 221.857L5.858 477.859c-7.811 7.811-7.811 20.475 0 28.285a19.938 19.938 0 0 0 14.143 5.857 19.94 19.94 0 0 0 14.143-5.857L256 284.287l221.857 221.857c3.905 3.905 9.024 5.857 14.143 5.857s10.237-1.952 14.143-5.857c7.811-7.811 7.811-20.475 0-28.285L284.286 256.002z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" id="open-menu">
    <path d="M492 236H20c-11.046 0-20 8.954-20 20s8.954 20 20 20h472c11.046 0 20-8.954 20-20s-8.954-20-20-20zm0-160H20C8.954 76 0 84.954 0 96s8.954 20 20 20h472c11.046 0 20-8.954 20-20s-8.954-20-20-20zm0 320H20c-11.046 0-20 8.954-20 20s8.954 20 20 20h472c11.046 0 20-8.954 20-20s-8.954-20-20-20z"></path>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="instagram">
    <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id=youtube>
    <path d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"/>
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="stackoverflow">
    <path d="M21 27v-8h3v11H0V19h3v8h18z"></path><path d="M17.1.2L15 1.8l7.9 10.6 2.1-1.6L17.1.2zm3.7 14.7L10.6 6.4l1.7-2 10.2 8.5-1.7 2zM7.2 12.3l12 5.6 1.1-2.4-12-5.6-1.1 2.4zm-1.8 6.8l13.56 1.96.17-2.38-13.26-2.55-.47 2.97zM19 25H5v-3h14v3z"></path>
  </symbol>
</svg>


<footer class="footer">
  <div class="footer_inner wrap pale">
    <img src='/icons/apple-touch-icon.png' class="icon icon_2 transparent" alt="Fundamentals of Analytics">
    <p>Copyright&nbsp;<span class="year"></span>&nbsp;FUNDAMENTALS OF ANALYTICS. All Rights Reserved</p><a class="to_top" href="#documentTop">
  <svg class="icon">
  <use xlink:href="#arrow"></use>
</svg>
</a>

  </div>
</footer>

    <script type="text/javascript" src="/js/bundle.min.617c4c3549a10c9fe7e1bb91e87f0722f6a285b59e742c7123c755df9fb33530bae76060ebd303966dd0e1c09813e679f8042802b7fd059315ef1345f0429ad2.js" integrity="sha512-YXxMNUmhDJ/n4buR6H8HIvaihbWedCxxI8dV35&#43;zNTC652Bg69MDlm3Q4cCYE&#43;Z5&#43;AQoArf9BZMV7xNF8EKa0g==" crossorigin="anonymous"></script>
    
  </body>
</html>
